apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-example
data:
  city: Amsterdam
  contry: Netherlands
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cm-cmd-example
spec:
  template:
    spec:
      containers:
      - name: env
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["echo Hello from ${CITY}!"]   
        env:
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: manifest-example
              key: city
      restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-vol-example
spec:
  restartPolicy: Never
  containers:
  - name: mypod
    image: alpine:latest
    command: ["sh", "-c", "echo \"The city is: $(cat /etc/config/city)\""]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: manifest-example
